-- DIFFERENCE BETWEEN WHERE AND HAVING CLAUSE

SELECT * FROM student_info;

SELECT SOURCE_OF_JOINING,COUNT(*) AS TOTAL FROM student_info GROUP BY SOURCE_OF_JOINING; 

-- FIND THE LEAD SOURCES THROUGH WHICH MORE THAN 1 PERSON HAS REGISTERED.

-- SELECT SOURCE_OF_JOINING,COUNT(*) AS TOTAL FROM student_info GROUP BY SOURCE_OF_JOINING WHERE TOTAL >1

-- HERE WHERE CLAUSE DOESNOT WORK BECAUSE IT IS USED TO FILTER THE INIDIVIDUAL RECORD BEFORE AGGREGATION. 

SELECT SOURCE_OF_JOINING,COUNT(*) AS TOTAL FROM student_info GROUP BY SOURCE_OF_JOINING HAVING TOTAL >1; 

-- HAVING IS USED TO FILTER RECORD AFTER GROUPING.

-- FIND TOTAL NUMBER OF PEOPLE WHO JOINED THROUGH LINKEDIN.
SELECT source_of_joining,count(*) from student_info GROUP BY source_of_joining HAVING source_of_joining="LinkedIn";

SELECT source_of_joining,count(*) from student_info WHERE source_of_joining="LinkedIn" GROUP BY source_of_joining ;

-- FIND LOCATION FROM WHICH MORE THAN 1 STUDENT HAS JOINED & EXPERIENCE IS MORE THEN 3 YEARS.
SELECT location,count(*) as total from student_info where years_of_exp>3 GROUP BY LOCATION HAVING TOTAL >1;

-- WHERE IS USED BEFORE GROUP BY AND DO FILTERING INDIVIDUAL RECORDS.alter
-- HAVING IS USED AFTER GROUP BY AND DO FILTERING AGGREATED RECORDS.alter
-- WE CAN USE WHERE AND HAVING IN SAME QUERY.
